//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketServices()
        {
            this.MarketServicePayments = new HashSet<MarketServicePayments>();
            this.MarketServiceStateHistory = new HashSet<MarketServiceStateHistory>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> ServiceSum { get; set; }
        public Nullable<decimal> ContractSum { get; set; }
        public string ServiceComment { get; set; }
        public Nullable<int> ServicePayFormId { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> StateId { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public string CreatorId { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTimeOffset> DeleteDate { get; set; }
        public string DeleterId { get; set; }
        public string RecipientName { get; set; }
        public string ClaimNumber { get; set; }
        public string TenderNumber { get; set; }
        public Nullable<System.DateTime> TenderDate { get; set; }
        public Nullable<decimal> BudgetSum { get; set; }
        public string Comment { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual MarketServicePayForms MarketServicePayForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketServicePayments> MarketServicePayments { get; set; }
        public virtual MarketServiceStates MarketServiceStates { get; set; }
        public virtual MarketServiceTypes MarketServiceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketServiceStateHistory> MarketServiceStateHistory { get; set; }
    }
}
