//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OwnAgentEntities : DbContext
    {
        public OwnAgentEntities()
            : base("name=OwnAgentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BillCapitalizationTypes> BillCapitalizationTypes { get; set; }
        public virtual DbSet<Spend> Spend { get; set; }
        public virtual DbSet<SpendBills> SpendBills { get; set; }
        public virtual DbSet<SpendBillTypes> SpendBillTypes { get; set; }
        public virtual DbSet<SpendCategory> SpendCategory { get; set; }
        public virtual DbSet<SpendVector> SpendVector { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
