//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpendBills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpendBills()
        {
            this.Spend = new HashSet<Spend>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public Nullable<decimal> StartAmount { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public Nullable<int> CapitalizationTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comment { get; set; }
        public string UserSid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int OrderNum { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual BillCapitalizationTypes BillCapitalizationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spend> Spend { get; set; }
        public virtual SpendBillTypes SpendBillTypes { get; set; }
    }
}
