//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spend
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int VectorId { get; set; }
        public int CategoryId { get; set; }
        public double Sum { get; set; }
        public string Comment { get; set; }
        public string UserSid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> BillId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SpendCategory SpendCategory { get; set; }
        public virtual SpendVector SpendVector { get; set; }
        public virtual SpendBills SpendBills { get; set; }
    }
}
