//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpendTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpendTransfer()
        {
            this.Spend = new HashSet<Spend>();
        }
    
        public int Id { get; set; }
        public int BillFromId { get; set; }
        public int BillToId { get; set; }
        public double Sum { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Enabled { get; set; }
        public string Comment { get; set; }
        public string UserSid { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spend> Spend { get; set; }
        public virtual SpendBills SpendBills { get; set; }
        public virtual SpendBills SpendBills1 { get; set; }
    }
}
